name: README build
on:
  schedule:
    - cron: "0 0 * * *"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - name: Get Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: python -m pip install -r cache/requirements.txt
      - name: Update README file
        env:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          USER_NAME: ${{ secrets.USER_NAME }}
        run: python readmeBuilder.py
      - name: Commit changes
        run: |-
          git add .
          git diff
          git config --global user.email "github-actions-bot@andreastar.github.io"
          git config --global user.name "AndreasTar/GitHub-Actions-Bot"
          git commit -m "Updated README" -a || echo "No changes to commit"
          git push